# Generated by Django 5.1.3 on 2026-07-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='file_data',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
    ]
