# Generated by Django 5.1.3 on 2026-07-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0002_userpdf_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedtext",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userpdf",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
