# Generated by Django 5.1.3 on 2026-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0003_alter_bookmark_id_alter_savedtext_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="pdf_path",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="userpdf",
            name="stored_path",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
