# Generated by Django 5.1.3 on 2026-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0004_bookmark_pdf_path_alter_userpdf_stored_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("audio_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
